#version: '3.8'

name: digital_portfolio

networks:
  digitalPortfolio:
    external: true

volumes:
  digitalPortfolioDB:
    external: true
  digitalPortfolioFiles:
    external: true

services:
  portfolioServer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: portfolioServer
    ports:
      - "8081:8080"
    environment:
      - Jwt:Issuer=${JWT_ISSUER}
      - Jwt:Audience=${JWT_AUDIENCE}
      - Jwt:Key=${JWT_KEY}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - Email=${EMAIL}
      - EmailPassword=${EMAIL_PASSWORD}
    volumes:
      - digitalPortfolioFiles:/files
    networks:
      - digitalPortfolio
    depends_on:
      - portfolioDB
  portfolioDB:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "8082:5432"
    volumes:
      - digitalPortfolioDB:/var/lib/postgresql/data
    networks:
      - digitalPortfolio
  portfolio_frontend:
    build:
      context: ../client
      dockerfile: Dockerfile
      target: dev  # Запуск именно сервера (start) реакт, а не сборка (build). См. докерфайл реакта. Измените на prod в продакшене
    restart: always
    container_name: portfolioFrontend
    ports:
      - "8083:3000"
    volumes:
      - ../client:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true # Обеспечивает работу hot reload
      - WDS_SOCKET_HOST=localhost #Следующие две настройки для работы hot reload
      - WDS_SOCKET_PORT=80 # По умолчанию hot reload подключается к localhost:3000, измениьте эти перемнные, если у вас не так
    # nginx должен быть настроен, чтобы уметь проксировать вебсокеты
    networks:
      - digitalPortfolio
    depends_on:
      - portfolioServer
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./:/etc/nginx/conf.d
    networks:
      - digitalPortfolio
    depends_on:
      - portfolioServer