version: '3.8'

name: digital_portfolio

networks:
  digitalPortfolio:
    external: true

volumes:
  digitalPortfolioDB:
    external: true
  digitalPortfolioFiles:
    external: true
# Все переменные окружения скрыты 😘
# Порты открыты для теста, в продакшене их нужно закрыть. (открыты, чтобы, например, подключиться к бд)
services:
  portfolio_server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: always
    container_name: portfolioServer
    ports:
      - "8081:8080"
      - "25:25"
    environment:
      - Jwt:Issuer=❤️❤️❤️❤️
      - Jwt:Audience=❤️❤️❤️❤️
      - Jwt:Key=❤️❤️❤️❤️❤️
      - POSTGRES_USER=❤️❤️
      - POSTGRES_PASSWORD=❤️❤️❤️❤️❤️
      - POSTGRES_DB=❤️❤️❤️❤️
      - Email=❤️❤️❤️❤️❤️
      - EmailPassword=❤️❤️❤️❤️❤️
    volumes:
      - digitalPortfolioFiles:/files
    networks:
      - digitalPortfolio
    depends_on:
      - portfolioDB
  portfolioDB:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=❤️❤️
      - POSTGRES_PASSWORD=❤️❤️❤️❤️❤️❤️❤️❤️❤️
      - POSTGRES_DB=❤️❤️❤️❤️❤️❤️❤️❤️❤️
    ports:
      - "8082:5432"
    volumes:
      - digitalPortfolioDB:/var/lib/postgresql/data
    networks:
      - digitalPortfolio
  portfolio_frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: portfolioFrontend
    ports:
      - "8083:80"
    networks:
      - digitalPortfolio
    depends_on:
      - portfolio_server
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./:/etc/nginx/conf.d
    networks:
      - digitalPortfolio
    depends_on:
      - portfolio_server